// Transaction types
export const TRANSACTION_TYPES = [
  { key: 'buy', label: 'Buy', icon: 'bi-cart', color: '#10B981' },
  { key: 'sell', label: 'Sell', icon: 'bi-tag', color: '#14B8A6' },
  { key: 'rent', label: 'Rent', icon: 'bi-key', color: '#8B5CF6' },
  { key: 'borrow', label: 'Borrow', icon: 'bi-arrow-left-right', color: '#3B82F6' },
  { key: 'share', label: 'Share', icon: 'bi-people', color: '#F59E0B' },
  { key: 'exchange', label: 'Exchange', icon: 'bi-repeat', color: '#EC4899' },
  { key: 'donate', label: 'Donate', icon: 'bi-gift', color: '#EF4444' },
];

// Item categories
export const CATEGORIES = [
  'Electronics', 'Furniture', 'Clothing', 'Books', 'Sports',
  'Garden', 'Kitchen', 'Tools', 'Toys', 'Vehicles', 'Other',
];

// Item conditions
export const CONDITIONS = [
  { key: 'new', label: 'Brand New' },
  { key: 'like_new', label: 'Like New' },
  { key: 'good', label: 'Good' },
  { key: 'fair', label: 'Fair' },
  { key: 'poor', label: 'Poor' },
];

// Sustainability metrics
export const SUSTAINABILITY_METRICS = [
  { key: 'co2_saved', label: 'CO₂ Saved', unit: 'kg', icon: 'bi-cloud' },
  { key: 'items_reused', label: 'Items Reused', unit: '', icon: 'bi-recycle' },
  { key: 'waste_diverted', label: 'Waste Diverted', unit: 'kg', icon: 'bi-trash3' },
  { key: 'community_impact', label: 'Community Impact', unit: 'actions', icon: 'bi-heart' },
];

// Sorting options
export const SORT_OPTIONS = [
  { key: 'newest', label: 'Newest First' },
  { key: 'oldest', label: 'Oldest First' },
  { key: 'price_low', label: 'Price: Low to High' },
  { key: 'price_high', label: 'Price: High to Low' },
  { key: 'distance', label: 'Nearest' },
  { key: 'popular', label: 'Most Popular' },
];

// API & App config
export const APP_NAME = 'ShareCircle';
export const APP_TAGLINE = 'Share Locally, Live Sustainably';
export const DEFAULT_RADIUS_KM = 10;
export const ITEMS_PER_PAGE = 12;

// Centralized mock items — shared by Browse, ItemDetails, etc.
export const MOCK_ITEMS = [
  {
    _id: '1',
    title: 'Garden Tools Set',
    description: 'Complete set of garden tools including spade, fork, and pruner. Great condition. Perfect for home gardeners who need quality tools without buying their own.',
    price: 0,
    mrp: 2500,
    deposit: 2500,
    transactionType: 'share',
    category: 'Garden',
    condition: 'good',
    location: { city: 'Ahmedabad', address: 'Satellite area' },
    owner: { name: 'Priya S.', email: 'priya@example.com' },
    images: ['/images/products/garden-tools.jpg'],
    createdAt: new Date(Date.now() - 3600000 * 2),
  },
  {
    _id: '2',
    title: 'Mountain Bicycle',
    description: 'Trek Marlin 5, barely used. Perfect for weekend rides. Comes with front suspension, 21-speed Shimano gears, and hydraulic disc brakes. Includes lock and helmet.',
    price: 8500,
    mrp: 15000,
    transactionType: 'sell',
    category: 'Sports',
    condition: 'like_new',
    location: { city: 'Ahmedabad', address: 'SG Highway area' },
    owner: { name: 'Arjun P.', email: 'arjun@example.com' },
    images: ['/images/products/mountain-bicycle.jpg'],
    createdAt: new Date(Date.now() - 86400000 * 3),
  },
  {
    _id: '3',
    title: 'Power Drill',
    description: 'Bosch cordless drill with 2 batteries and a carrying case. Ideal for DIY home projects. Barely used, purchased last year.',
    price: 200,
    mrp: 4500,
    deposit: 4500,
    rentPerDay: 200,
    transactionType: 'rent',
    category: 'Tools',
    condition: 'good',
    location: { city: 'Gandhinagar', address: 'Sector 21' },
    owner: { name: 'Rahul S.', email: 'rahul@example.com' },
    images: ['/images/products/power-drill.jpg'],
    createdAt: new Date(Date.now() - 86400000 * 1),
  },
  {
    _id: '4',
    title: 'Harry Potter Collection',
    description: 'Complete 7-book series, hardcover edition in excellent condition. Great for young readers or collectors. All books together as a set.',
    price: 50,
    mrp: 3500,
    deposit: 3500,
    borrowPerDay: 50,
    transactionType: 'borrow',
    category: 'Books',
    condition: 'good',
    location: { city: 'Ahmedabad', address: 'Navrangpura' },
    owner: { name: 'Sneha G.', email: 'sneha@example.com' },
    images: ['/images/products/harry-potter-books.jpg'],
    createdAt: new Date(Date.now() - 86400000 * 2),
  },
  {
    _id: '5',
    title: 'Standing Desk',
    description: 'Electric standing desk, adjustable height between 60-120cm. Minor scratches on the surface but fully functional. Great for home office setup.',
    price: 12000,
    mrp: 25000,
    transactionType: 'sell',
    category: 'Furniture',
    condition: 'fair',
    location: { city: 'Vadodara', address: 'Alkapuri' },
    owner: { name: 'Dev T.', email: 'dev@example.com' },
    images: ['/images/products/standing-desk.jpg'],
    createdAt: new Date(Date.now() - 86400000 * 5),
  },
  {
    _id: '6',
    title: 'Kids Toy Bundle',
    description: 'Assorted educational toys suitable for ages 3-6. Includes building blocks, puzzles, and art sets. All sanitized and in good condition.',
    price: 0,
    mrp: 0,
    transactionType: 'donate',
    category: 'Toys',
    condition: 'good',
    location: { city: 'Ahmedabad', address: 'Bodakdev' },
    owner: { name: 'Meera K.', email: 'meera@example.com' },
    images: ['/images/products/kids-toys.jpg'],
    createdAt: new Date(Date.now() - 86400000 * 4),
  },
  {
    _id: '7',
    title: 'MacBook Pro 2021',
    description: 'Apple MacBook Pro 14-inch, M1 Pro chip, 16GB RAM, 512GB SSD. Used for 1 year, excellent condition with all original accessories.',
    price: 95000,
    mrp: 199000,
    transactionType: 'sell',
    category: 'Electronics',
    condition: 'like_new',
    location: { city: 'Ahmedabad', address: 'Prahlad Nagar' },
    owner: { name: 'Vikram M.', email: 'vikram@example.com' },
    images: ['/images/products/macbook-pro.jpg'],
    createdAt: new Date(Date.now() - 86400000 * 1),
  },
  {
    _id: '8',
    title: 'Yoga Mat',
    description: 'Liforme yoga mat, 4.2mm thick, non-slip surface. Used for 6 months. Perfect for yoga, pilates, or home workouts.',
    price: 0,
    mrp: 3000,
    deposit: 3000,
    transactionType: 'share',
    category: 'Sports',
    condition: 'good',
    location: { city: 'Surat', address: 'Vesu' },
    owner: { name: 'Asha B.', email: 'asha@example.com' },
    images: ['/images/products/yoga-mat.jpg'],
    createdAt: new Date(Date.now() - 3600000 * 5),
  },
  {
    _id: '9',
    title: 'Fiction Book Collection',
    description: 'Collection of 20 bestselling fiction novels including works by Chetan Bhagat, Amish Tripathi, and more. Perfect for avid readers.',
    price: 500,
    mrp: 2000,
    transactionType: 'sell',
    category: 'Books',
    condition: 'good',
    location: { city: 'Rajkot', address: 'Race Course Road' },
    owner: { name: 'Pooja R.', email: 'pooja@example.com' },
    images: ['/images/products/fiction-books.jpg'],
    createdAt: new Date(Date.now() - 86400000 * 6),
  },
  {
    _id: '10',
    title: 'Camping Tent',
    description: '4-person dome tent, waterproof, easy setup. Perfect for weekend camping trips. Includes stakes and carry bag.',
    price: 300,
    mrp: 8000,
    deposit: 8000,
    rentPerDay: 300,
    transactionType: 'rent',
    category: 'Sports',
    condition: 'good',
    location: { city: 'Gandhinagar', address: 'Sector 9' },
    owner: { name: 'Kiran J.', email: 'kiran@example.com' },
    images: ['/images/products/camping-tent.jpg'],
    createdAt: new Date(Date.now() - 86400000 * 2),
  },
  {
    _id: '11',
    title: 'Air Purifier',
    description: 'Philips AC1215 air purifier, covers up to 49 sq.m. Includes HEPA filter. Working perfectly, just upgraded to a larger model.',
    price: 4000,
    mrp: 9000,
    transactionType: 'sell',
    category: 'Electronics',
    condition: 'good',
    location: { city: 'Ahmedabad', address: 'Maninagar' },
    owner: { name: 'Nilesh T.', email: 'nilesh@example.com' },
    images: ['/images/products/air-purifier.jpg'],
    createdAt: new Date(Date.now() - 86400000 * 3),
  },
  {
    _id: '12',
    title: 'Kitchen Mixer',
    description: 'Bosch kitchen stand mixer, 800W, 5L bowl. All attachments included. Selling because we received a new one as a gift.',
    price: 6000,
    mrp: 12000,
    transactionType: 'sell',
    category: 'Kitchen',
    condition: 'like_new',
    location: { city: 'Vadodara', address: 'Karelibaug' },
    owner: { name: 'Sonia P.', email: 'sonia@example.com' },
    images: ['/images/products/kitchen-mixer.jpg'],
    createdAt: new Date(Date.now() - 86400000 * 7),
  },
  {
    _id: '13',
    title: 'Baby Stroller',
    description: 'Chicco Bravo stroller, suitable for newborns to 3 years. Folds compactly. Neutral color, great condition with all accessories.',
    price: 0,
    mrp: 0,
    transactionType: 'donate',
    category: 'Toys',
    condition: 'good',
    location: { city: 'Ahmedabad', address: 'Thaltej' },
    owner: { name: 'Rupa S.', email: 'rupa@example.com' },
    images: ['/images/products/baby-stroller.jpg'],
    createdAt: new Date(Date.now() - 86400000 * 8),
  },
  {
    _id: '14',
    title: 'Acoustic Guitar',
    description: 'Yamaha F310 acoustic guitar with soft case and extra strings. Perfect for beginners or intermediate players looking to borrow and practice.',
    price: 150,
    mrp: 8000,
    deposit: 8000,
    borrowPerDay: 150,
    transactionType: 'borrow',
    category: 'Other',
    condition: 'good',
    location: { city: 'Surat', address: 'Adajan' },
    owner: { name: 'Manish K.', email: 'manish@example.com' },
    images: ['/images/products/acoustic-guitar.jpg'],
    createdAt: new Date(Date.now() - 86400000 * 4),
  },
  {
    _id: '15',
    title: 'Vintage Camera',
    description: 'Canon AE-1 35mm film camera in working condition. Great for photography enthusiasts who want to exchange for a digital camera or similar gear.',
    price: 0,
    mrp: 0,
    wantInReturn: 'Any working digital camera or mirrorless body',
    transactionType: 'exchange',
    category: 'Electronics',
    condition: 'fair',
    location: { city: 'Ahmedabad', address: 'Law Garden' },
    owner: { name: 'Rohan D.', email: 'rohan@example.com' },
    images: ['/images/products/air-purifier.jpg'],
    createdAt: new Date(Date.now() - 86400000 * 2),
  },
  {
    _id: '16',
    title: 'Electric Kettle',
    description: 'Prestige 1.5L electric kettle, brand new, purchased last week. Giving away to anyone in need.',
    price: 0,
    mrp: 0,
    transactionType: 'buy',
    category: 'Kitchen',
    condition: 'new',
    location: { city: 'Ahmedabad', address: 'Paldi' },
    owner: { name: 'Anita M.', email: 'anita@example.com' },
    images: ['/images/products/kitchen-mixer.jpg'],
    createdAt: new Date(Date.now() - 86400000 * 1),
    mrp: 1500,
    price: 1200,
  },
];
